on:
  push:
    branches:
    - main
    - release/*
    
jobs:
  deploy:
    name: Deploy stuff
    runs-on: ubuntu-22.04
    steps:
    - name: Terraform action
      uses: Yellow-Box-Software/terraform-action@v2.5
      with:
        # Terraform CLI arguments
        args: init # default is --help
